set(QStm_SRCS
    ../includes/QStm
    ../src/private/p_qstm_base_setting.cpp
    ../src/private/p_qstm_base_setting.h
    ../src/private/p_qstm_result_info.cpp
    ../src/private/p_qstm_result_info.h
    ../src/private/p_qstm_setting_manager.cpp
    ../src/private/p_qstm_setting_manager.h
    ../src/private/p_qstm_startup.cpp
    ../src/private/p_qstm_startup.h
    ../src/qstm.h
    ../src/qstm_cache_pool.cpp
    ../src/qstm_cache_pool.h
    ../src/qstm_const.h
    ../src/qstm_crypto_util.cpp
    ../src/qstm_crypto_util.h
    ../src/qstm_currency.cpp
    ../src/qstm_currency.h
    ../src/qstm_fileinfo.cpp
    ../src/qstm_fileinfo.h
    ../src/qstm_global.h
    ../src/qstm_log.cpp
    ../src/qstm_log.h
    ../src/qstm_logger.cpp
    ../src/qstm_logger.h
    ../src/qstm_macro.h
    ../src/qstm_message.cpp
    ../src/qstm_message.h
    ../src/qstm_meta_enum.h
    ../src/qstm_meta_types.cpp
    ../src/qstm_meta_types.h
    ../src/qstm_network_types.cpp
    ../src/qstm_network_types.h
    ../src/qstm_object.cpp
    ../src/qstm_object.h
    ../src/qstm_object_wrapper.cpp
    ../src/qstm_object_wrapper.h
    ../src/qstm_result.cpp
    ../src/qstm_result.h
    ../src/qstm_result_info.cpp
    ../src/qstm_result_info.h
    ../src/qstm_setting_base.cpp
    ../src/qstm_setting_base.h
    ../src/qstm_setting_manager.cpp
    ../src/qstm_setting_manager.h
    ../src/qstm_startup.cpp
    ../src/qstm_startup.h
    ../src/qstm_types.cpp
    ../src/qstm_types.h
    ../src/qstm_types_const.h
    ../src/qstm_url.cpp
    ../src/qstm_url.h
    ../src/qstm_util_date.cpp
    ../src/qstm_util_date.h
    ../src/qstm_util_double.cpp
    ../src/qstm_util_double.h
    ../src/qstm_util_formatting.cpp
    ../src/qstm_util_formatting.h
    ../src/qstm_util_meta_object.cpp
    ../src/qstm_util_meta_object.h
    ../src/qstm_util_path.cpp
    ../src/qstm_util_path.h
    ../src/qstm_util_variant.cpp
    ../src/qstm_util_variant.h
    ../src/qstm_vvm.cpp
    ../src/qstm_vvm.h
)
